server:
  port: 8080
  context-path: /springboot
  
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  thymeleaf:
    suffix: .ftl
    content-type: text/html; charset=utf-8
    cache: false
    encoding: UTF-8
