server:
  port: 8080
  compression:
    enabled: true
    mime-types:
    - text/html
    - text/css
    - text/javascript
    - application/json
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopxx-boot?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.MySQLDialect

  freemarker:
    settings:
      tag_syntax: auto_detect
      classic_compatible: true
